### ISSUE TITLE
get_bgp_neighbors_detail: Waiting for 3 arguments while meta-data shows only 2 mandatory

### ISSUE THREAD

**Issue by mab27** [StackStorm-Exchange/stackstorm-napalm#14]
Trying the napalm pack on Junos devices.
Having some issues with the **_get_bgp_neighbors_detail_** action.

`napalm.get_bgp_neighbors works` fine
```
mab@mab-infra:/opt/stackstorm/packs/napalm$ sudo st2 run napalm.get_bgp_neighbors hostname=vmx1
..
id: 58fe1a8b7cae220853c4254d
status: succeeded
parameters: 
  hostname: vmx1
result: 
  exit_code: 0
  result:
    raw:
      172.16.0.40:
        address_family: {}
        description: ''
        is_enabled: true
        is_up: false
        local_as: 101
        remote_as: 102
        remote_id: ''
        uptime: 9899
  stderr: ''
  stdout: ''
mab@mab-infra:/opt/stackstorm/packs/napalm$ 
```
But the `napalm.get_bgp_neighbors_detail` isn't
```
mab@mab-infra:/opt/stackstorm/packs/napalm$ sudo st2 run napalm.get_bgp_neighbors_detail hostname=vmx1 neighbor=172.16.0.40
.
id: 58fe1a927cae220853c42550
status: failed
parameters: 
  hostname: vmx1
  neighbor: 172.16.0.40
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
TypeError: run() takes exactly 3 arguments (2 given)
"
  stdout: ''
```

Looks like the action is expecting 3 argumets while the meta-data shows only 2 being mandatory.

```
mab@mab-infra:/opt/stackstorm/packs/napalm$
mab@mab-infra:/opt/stackstorm/packs/napalm$ sudo st2 run napalm.get_bgp_neighbors_detail hostname=vmx1 -h

Get a detailed BGP neighbor from a device using NAPALM.

Required Parameters:
    hostname
        The hostname of the device to connect to. Driver must be specified if
        hostname is not in configuration. Hostname without FQDN can be given
        if device is in configuration.
        Type: string

    neighbor
        The BGP neighbor to get details of.
        Type: string

Optional Parameters:
    driver
        Device driver name for connecting to device, see
        https://napalm.readthedocs.io/en/latest/support/index.html for list.
        Type: string

    port
        port for accessing device
        Type: string

    credentials
        The credentials group which contains the username and password to log
        in
        Type: string

    htmlout
        In addition to the normal output also includes html output.
        Type: boolean

    env
        Environment variables which will be available to the script.
        Type: object

    timeout
        Action timeout in seconds. Action will get killed if it doesn't finish
        in timeout seconds.
        Type: integer
        Default: 600
```
