### ISSUE TITLE
Missing credentials section in `config.schema.yaml`

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm-Exchange/stackstorm-napalm#22]
We refer to a credentials section in `napalm.yaml.example`:

```yaml
credentials:
  core:
    username: myuser
    password: mypassword
```

But our `config.schema.yaml` doesn't seem to have any mention of that section. Needs fixing, so that (A) we properly validate that config, and (B) we validate our example config against it
