### ISSUE TITLE
get_interfaces has cryptic error when you typo the interface name

### ISSUE THREAD

**Issue by Mierdin** [StackStorm-Exchange/stackstorm-napalm#23]
Should improve this. Need to detect when result is empty and return useful message first.

```
vagrant@st2vagrant:~$ st2 run napalm.get_interfaces hostname=vsrx01 interface="foobar0/0/1"
..
id: 595adcddc4da5f0521ea9082
status: failed
parameters:
  hostname: vsrx01
  interface: foobar0/0/1
result:
  exit_code: 0
  result: '''NoneType'' object does not support item assignment'
  stderr: 'st2.actions.python.NapalmGetInterfaces: ERROR    ''NoneType'' object does not support item assignment

    '
  stdout: ''
```
