### ISSUE TITLE
"get_route_to" action failing

### ISSUE THREAD

**Issue by mab27** [StackStorm-Exchange/stackstorm-napalm#29]
Seems like the **get_route_to** action behaves inconsistently depending on the network driver.
I have a situation where two devices (Juniper and Arista) having the same route in their table, the action works fine towards Arista and fails towards Juniper.
And the most surprising is the error message!

**On Arista vEOS --> Works OK**
```
mab@mab-infra:~/automation$ sudo st2 run napalm.get_route_to hostname=arista1 destination=10.10.1.0/24
.
id: 59834ac87cae2206da22f34b
status: succeeded
parameters: 
  destination: 10.10.1.0/24
  hostname: arista1
result: 
  exit_code: 0
  result:
    raw:
      10.10.1.0/24:
      - age: 0
        current_active: true
        inactive_reason: noReason
        last_active: true
        next_hop: 172.16.0.10
        outgoing_interface: Ethernet1
        preference: 200
        protocol: eBGP
        protocol_attributes:
          as_path: '65010'
          communities: []
          local_as: 65070
          local_preference: 100
          metric: 0
          preference2: 0
          remote_address: 172.16.0.10
          remote_as: 65010
        routing_table: default
        selected_next_hop: true
  stderr: ''
  stdout: ''
```

**On  Juniper vMX --> NOK**
```
mab@mab-infra:~/automation$ sudo st2 run napalm.get_route_to hostname=vmx1 destination=10.10.1.0/24
.
id: 598347777cae2206da22f348
status: failed
parameters: 
  destination: 10.10.1.0/24
  hostname: vmx1
result: 
  exit_code: 0
  result: 'Cannot retrieve routes! Reason: The value 10.10.1.0/24 for argument destination is of <type ''unicode''>. Argument values must be a string, boolean, or list/tuple of strings and booleans.'
  stderr: 'st2.actions.python.NapalmGetRouteTo: ERROR    Cannot retrieve routes! Reason: The value 10.10.1.0/24 for argument destination is of <type ''unicode''>. Argument values must be a string, boolean, or list/tuple of strings and booleans.

    '
  stdout: ''
```

**On the vMX, the route to 10.10.1.0/24 is there:**

```
mab@vmx1> show route 10.10.1.0/24    

inet.0: 7 destinations, 7 routes (7 active, 0 holddown, 0 hidden)
+ = Active Route, - = Last Active, * = Both

10.10.1.0/24       *[BGP/170] 00:02:11, localpref 100
                      AS path: 65010 I, validation-state: unverified
                    > to 172.16.0.10 via ge-0/0/1.0

mab@vmx1> 
```

**Comment by Mierdin** [comment]
I am testing with vSRX not a vMX, so YMMV - but I suspect this is because you're passing the prefix length (BTW you also don't need to use `sudo` for the st2 client).

Note that when I pass the prefix length like you did, I don't get an error, but I definitely don't get the results I want:

```
vagrant@st2vagrant:~$ st2 run napalm.get_route_to hostname=vsrx01 destination=10.10.1.0/24
..
id: 59853514c4da5f054379fea4
status: succeeded
parameters:
  destination: 10.10.1.0/24
  hostname: vsrx01
result:
  exit_code: 0
  result:
    raw: {}
  stderr: ''
  stdout: ''
```

Yet, works when I remove the prefix length:

```
vagrant@st2vagrant:~$ st2 run napalm.get_route_to hostname=vsrx01 destination=10.10.1.0
..
id: 59853525c4da5f054379fea7
status: succeeded
parameters:
  destination: 10.10.1.0
  hostname: vsrx01
result:
  exit_code: 0
  result:
    raw:
      0.0.0.0/0:
      - age: 264
        current_active: true
        inactive_reason: ''
        last_active: true
        next_hop: 10.0.2.2
        outgoing_interface: ge-0/0/0.0
        preference: 12
        protocol: Access-internal
        protocol_attributes: {}
        routing_table: inet.0
        selected_next_hop: true
  stderr: ''
  stdout: ''
vagrant@st2vagrant:~$
```

Same behavior just using NAPALM at the interpreter.

```
(napalm) vagrant@st2vagrant:/opt/stackstorm/virtualenvs/napalm$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import junos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named junos
>>> import napalm
>>> driver = napalm.get_network_driver('junos')
>>> device = driver(hostname='vsrx01', username='root', password='Juniper', optional_args={'port': 22})
>>> device.open()
>>> device.get_route_to(destination="10.10.1.0/24")
{}
>>> device.get_route_to(destination="10.10.1.0")
{u'0.0.0.0/0': [{'protocol': u'Access-internal', 'last_active': True, 'outgoing_interface': u'ge-0/0/0.0', 'current_active': True, 'routing_table': u'inet.0', 'next_hop': u'10.0.2.2', 'selected_next_hop': True, 'preference': 12, 'inactive_reason': u'', 'age': 967, u'protocol_attributes': {}}]}
```

The help for the `destination` parameter for this action is modeled after the [equivalent documentation](http://napalm.readthedocs.io/en/latest/base.html#napalm_base.base.NetworkDriver.get_route_to) for the NAPALM function, which almost always seems to hint at an IP address to be used here, except for the phrase `The destination prefix to be used when filtering the routes.`.

I'd recommend opening an issue with NAPALM and at the very least, get this cleared up in the docs, and best-case, get the behavior inconsistency sorted out. Looks like they're [doing very little in the JunOS driver](https://github.com/napalm-automation/napalm-junos/blob/develop/napalm_junos/junos.py#L1379) to the `destination` parameter; just passing it through to pyez. If pyez handles this parameter differently than other libs, they may want to add a function to clean this up.

Ping me on slack if you have any questions on getting in touch with those folks.
