### ISSUE TITLE
[feature request] make it possible to specify a command to set to device to the parameter of napalm.loadconfig action directly

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm-Exchange/stackstorm-napalm#37]
## Background/Problem
We can set some configurations to an appliance by the `napalm.loadconfig` action.
But, this requires the filepath in which some configurations are written.

It's hard to make a simple Rule (without WorkFlow) to set some configuration to an appliance using this action, because we have to make a configuration file before running `napalm.loadconfig`.

## Proposal
If we could specify a command to the parameter directly, I thought this will be more useful.

Thank you.

**Comment by Mierdin** [comment]
@userlocalhost Have you looked at the `napalm.cli` action? This allows you to run one-off commands on a device.

**Comment by manji-0** [comment]
@Mierdin

> This allows you to run one-off commands on a device.

 I tried. but `napalm.cli` can't set one-off configuration line.

```
$ st2 run napalm.cli hostname='172.16.0.101' commands='set interfaces lo0 disable'
..
id: 5a0aa97fbda1906b9535ed51
status: succeeded
parameters: 
  commands:
  - set interfaces lo0 disable
  hostname: 172.16.0.101
result: 
  exit_code: 0
  result:
    raw:
      set interfaces lo0 disable: 'invalid command: set interfaces lo0 disable: RpcError(severity: error, bad_element: interfaces, message: syntax error, expecting <command>)'
    raw_array:
      set interfaces lo0 disable:
      - 'invalid command: set interfaces lo0 disable: RpcError(severity: error, bad_element: interfaces, message: syntax error, expecting <command>)'
  stderr: ''
  stdout: ''
```

and can't enter configure mode. (timeout)

```
$ st2 run napalm.cli hostname='172.16.0.101' commands='configure','set interfaces lo0 disable','commit and-quit'
............................................................
id: 5a0aaac6bda1906b9535ed54
status: succeeded
parameters: 
  commands:
  - configure
  - set interfaces lo0 disable
  - commit and-quit
  hostname: 172.16.0.101
result: 
  exit_code: 0
  result:
    raw:
      commit and-quit: 'invalid command: commit and-quit: RpcError(severity: error, bad_element: commit, message: syntax error, expecting <command> or </command>)'
      configure: 'invalid command: configure: RpcTimeoutError(host: 172.16.0.101, cmd: command, timeout: 60)'
      set interfaces lo0 disable: 'invalid command: set interfaces lo0 disable: RpcTimeoutError(host: 172.16.0.101, cmd: command, timeout: 60)'
    raw_array:
      commit and-quit:
      - 'invalid command: commit and-quit: RpcError(severity: error, bad_element: commit, message: syntax error, expecting <command> or </command>)'
      configure:
      - 'invalid command: configure: RpcTimeoutError(host: 172.16.0.101, cmd: command, timeout: 60)'
      set interfaces lo0 disable:
      - 'invalid command: set interfaces lo0 disable: RpcTimeoutError(host: 172.16.0.101, cmd: command, timeout: 60)'
  stderr: ''
  stdout: ''
```

I think, `napalm.cli` can't handle sequential commands.

**Comment by manji-0** [comment]
p.s. I tried it on vagrant.

> model: FIREFLY-PERIMETER
> os_version: 12.1X47-D15.4

```
vagrant@st2:~$ st2 run napalm.get_facts hostname='172.16.0.101'
id: 5a0aadecbda1906b9535ed57
status: succeeded
parameters: 
  hostname: 172.16.0.101
result: 
  exit_code: 0
  result:
    raw:
      fqdn: r1
      hostname: r1
      interface_list:
      - ge-0/0/0
      - gr-0/0/0
      - ip-0/0/0
      - lsq-0/0/0
      - lt-0/0/0
      - mt-0/0/0
      - sp-0/0/0
      - ge-0/0/1
      - ge-0/0/2
      - ge-0/0/3
      - .local.
      - dsc
      - gre
      - ipip
      - irb
      - lo0
      - lsi
      - mtun
      - pimd
      - pime
      - pp0
      - ppd0
      - ppe0
      - st0
      - tap
      - vlan
      model: FIREFLY-PERIMETER
      os_version: 12.1X47-D15.4
      serial_number: 6dae7671ee8f
      uptime: 55394
      vendor: Juniper
```
