### ISSUE TITLE
napalm.facts https error

### ISSUE THREAD

**Issue by mmihir82** [StackStorm-Exchange/stackstorm-napalm#44]
Hello 
Getting error when fetching the napalm.facts 
```
requests.exceptions.ProxyError: HTTPSConnectionPool(host='leafsw01', port=22): Max retries exceeded with url: /ins (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 404 Not Found',)))
```
Not sure why it is using proxy, under `config/napalm.yaml` this is what I have configured:
```
devices:
  - hostname: leafsw01
    driver: nxos
    port: 22
    credentials: ro
```
