### ISSUE TITLE
SSL Error driver NXOS

### ISSUE THREAD

**Issue by mmihir82** [StackStorm-Exchange/stackstorm-napalm#46]
Hello 
Running to road-block when using driver nxos. Error: 
```
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
```
How to bypass or accept the certificate from the nxos api?

**Comment by Mierdin** [comment]
Best answer: Fix the certificate issue.

Easy answer: The NXOS NAPALM driver [exposes a `transport` parameter](https://github.com/napalm-automation/napalm/blob/develop/napalm/nxos/nxos.py#L196), but we're not exposing it within this pack. We're only statically pulling `port` out of the configuration and populating `optional_args` with only that.

Being able to change the transport parameter would allow you to select HTTP, I'd imagine. Should be pretty straightforward to add, but IMO we should add a configuration for all optional params while we're at it, not just this one.

**Comment by mmihir82** [comment]
Hello @Mierdin 
Thanks for your answer. Question I had is how to fix SSL certificate? Is it at the switch?
I did added `port = 22`, but it seem nxos using nxapi which is 443.

**Comment by mmihir82** [comment]
Hello @Mierdin Is it possible to pass variable using jinja2 for devices. 
```
---
html_table_class: napalm
credentials:
  default:
     username: admin
     password: ChangeME

devices:
   - hostname: '{{ hostname }}'
     driver: '{{ driver }}'
     credentials: default
```
I am getting error when I reload st2clt`  error: 'Failed to render dynamic configuration value for key "credentials.default.devices.0.hostname" with value "{{ hostname }}" for pack "napalm" config: <class ''jinja2.exceptions.UndefinedError''> ''hostname'' is undefined '`
