### ISSUE TITLE
InsecureRequestWarning: Unverified HTTPS request

### ISSUE THREAD

**Issue by muhammad-rafi** [StackStorm-Exchange/stackstorm-napalm#71]
Sorry I am new to stackstorm, I am wondering, in stackstorm if we can turn off the InsecureRequestWarning warning for the lab devices whilst testing it ? I did a work around and edit the `/actions/lib/action.py`  with the below 

```
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```
I am sure there should be a better way to handle this, please advise ? 

I dont even see any input that takes optional arg, where I can provide ssl_verify options

**Comment by floatingstatic** [comment]
Hi @muhammad-rafi , this sounds like something you would probably be better off setting in the napalm driver configuration itself. What type of device is this or which napalm driver are you using here?

**Comment by muhammad-rafi** [comment]
thanks for the response, I am using `nxos` driver

**Comment by floatingstatic** [comment]
Have your tried passing `ssl_verify` set to `False` as `optional_args` in the nxos driver configuration?

https://napalm.readthedocs.io/en/latest/support/index.html?highlight=ssl_verify#list-of-supported-optional-arguments

**Comment by muhammad-rafi** [comment]
yes, I normally do when I use napalm without stackstorm but in the stackstorm napalm, I dont know how to achieve this, so I tried this but did not make any difference, I edit again `/actions/lib/action.py`

```    
        optional_args = {}

        if not found_device['port']:
            pass
        else:
            optional_args = {'port': int(found_device['port'])}

        if 'secret' in login:
            optional_args = {'secret': login['secret']}

        if 'key_file' in login:
            optional_args = {'key_file': str(login['key_file'])}
            login['password'] = None

        if 'ssl_verify' in login:
            optional_args = {'ssl_verify': login['ssl_verify']}
```
see the last lines added above and then edit the `/opt/stackstorm/packs/napalm/actions/get_config.yaml`

with the following 
```
    optional_args:
        type: "string"
        description: "pass the optional args key value pair e.g. ssl_verify=False"
        required: false
        position: 5
```

so I can see the optional_args input field, but there are two issues, my original still there as this did not make any difference, other thing if I use same approach, then I will have to edit all the actions.

**Comment by muhammad-rafi** [comment]
Just to let you know I also tried this with '/opt/stackstorm/configs/napalm.yaml` but still no joy 
```
devices:
- hostname: nxos-sw01
  port: 443
  driver: nxos
  credentials: core
  ssl_verify: False
```
